name: Test Deploy
on:
  push:
    branches: [ main ]

jobs:
  test-vercel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo "Branch is ${{ github.ref }}"
    - run: echo "Secrets exist - ORG ${{ secrets.VERCEL_ORG_ID != '' }}"
    - run: echo "Secrets exist - PROJECT ${{ secrets.VERCEL_PROJECT_ID != '' }}"
    - run: echo "Secrets exist - TOKEN ${{ secrets.VERCEL_TOKEN != '' }}"